kind: pipeline
type: docker
name: test
steps:
- name: nix-build
  image: nixos/nix
  volumes:
  - name: nix
    path: /nix
  commands:
  - nix-build
  - gunzip < result > image.tar

- name: publish
  image: gcr.io/go-containerregistry/crane
  environment:
    DOCKER_USER: pr0ger
    DOCKER_PASS:
      from_secret: docker_password
  volumes:
  - name: nix
    path: /nix
  commands:
  - crane auth login index.docker.io -u $DOCKER_USER -p $DOCKER_PASS
  - crane push image.tar pr0ger/drone-convert-dhall:latest

volumes:
- name: nix
  temp: {}
