kind: pipeline
type: docker
name: test
steps:
- name: test
  image: haskell:8.10.1
  commands:
  - cabal update
  - cabal install --only-dependencies
  - cabal build --only-dependencies --enable-tests
  - cabal build --enable-tests all
  - cabal test all
