kind: pipeline
type: docker
name: test
steps:
- name: nix-build
  image: nixos/nix
  commands:
  - nix-build
- name: publish
  image: plugins/drone
  environment:
    DOCKER_USER: pr0ger
    DOCKER_PASS:
      from_secret: docker_password
  commands:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker load -i result
  - docker push pr0ger/drone-convert-dhall:latest
  - docker rmi pr0ger/drone-convert-dhall:latest
