kind: pipeline
type: docker
name: test
steps:
- name: nix-build
  image: nixos/nix
  commands:
  - nix-build
- name: stack-test
  image: haskell:latest
  commands:
  - stack setup
  - stack test
- name: test
  image: haskell:8.10.1
  commands:
  - cabal update
  - cabal install --only-dependencies
  - cabal build --only-dependencies --enable-tests
  - cabal build --enable-tests all
  - cabal test all
