kind: pipeline
type: docker
name: test
steps:
- name: nix-build
  image: nixos/nix
  commands:
  - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
  - nix-channel --update
  - nix-build
