kind: pipeline
type: docker
name: test
steps:
- name: nix-build
  image: nixos/nix
  volumes:
  - name: nix
    path: /nix
  commands:
  - nix-build

- name: publish
  image: pr0ger/drone-crane
  settings:
    username: pr0ger
    password:
      from_secret: docker_password
    repo: pr0ger/drone-convert-dhall
    tags: latest
  volumes:
  - name: nix
    path: /nix

volumes:
- name: nix
  temp: {}
